--- 

# this file is dynamically called by include_vars operation.
user:
  name: ubuntu
  group: sudo # wheel when centos
  pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDH+HHxNMMiGXIB4hwE7s8u3hdUiW37ON/XApnjiIStgPP6uA0+jhvvoAXqvV7Taxkp4sXXsbSsrPvIaEHoIS6m9HwjrUebvLsWhHohzFh/GG2GUAwYf36RURRwNX11g+9iBQtFmmBCELSRXjbIG48rQcmJS/CleHWKkmBJRhX1T48pys9HKTGOECJS63h4nfNQ5tSaKL7DQERimyOxMztg57mZsT2Gt/pvEjYL6/r1qEYUC2D758bdDGUGPSc2T1AYMAsmAOvvXlyPftd4g49qecqVJe8Bl23UGc5oKQLV5quV1S2rMTH9XtYhp0/QhmnagBLJ5zYPjHFjeUdM1b3H ansible-generated on localhost.localdomain"
  # git_repos:
  #   - repo: "https://github.com/jinshikoike/dotfile.git"
  #     dest: "/.dotfiles"
  #   - repo: "https://github.com/jinshikoike/dotfile.git"

  profile_lines:
    - export DB_HOST="127.0.0.1"
    - export DB_USER="root"
    - export DB_PASSWORD="root"
    - export PATH="/usr/local/go/bin:$PATH"
  # this is called after secrets file is uploaded
  # below commands is executed under home directory
  run_commands:
    - echo $TES_TES
